#!/bin/bash
##############################
# BIZBASH
##############################

# INITIALIZATION ==========

if [[ ! ( -s $HOME/biznet ) ]]; then
  git clone https://github.com/biznach/biznet
  if [[ -s $HOME/biznet ]]; then
    cd $HOME/biznet
      bizgit biznet
    cd $HOME
  fi
fi

#if [[ -s $HOME/biznet/bizkey ]]; then
  #source bizkey
#fi

if [[ -s $HOME/.bashrc ]]; then
  if grep -Fq "BIZNET" $HOME/.bashrc; then
    # code if found
    echo "BizNet Initialized" >/dev/null
  else
    if [[ -s $HOME/biznet/bizinclude ]]; then
      cat $HOME/biznet/bizbashinc >> $HOME/.bashrc
    fi
  fi
fi

# BIZPATH ==========

export PATH=$HOME/biznet:$PATH

# ALIASES ==========

# some more ls aliases
alias l1='ls -1'
alias lla='ls -la'
alias ll='ls -a'
alias ll='ls -l'
alias read='less ./README.txt'

# VARIABLES ==========

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[1;36m'
NC='\033[0m' # No Color

# variable for friendly host name
if [[ -s $HOME/.bizconfig ]]; then
  # export first line of .bizconfig file as env variable
  export BIZHOST=$( awk '{print $1; exit}' $HOME/.bizconfig )
else
  export BIZHOST="biznet"
fi

# save history after every command
#export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
export PROMPT_COMMAND="history -a; history -c; history -r"

# BIZPROMT ==========

case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@$BIZHOST\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@$BIZHOST:\w\$ '
fi
unset color_prompt

# WELCOME ==========

if [[ ! -z $( command -v figlet ) ]]; then
  figlet '     BizNet'
else
  echo -e '\n     BizNet BizNet BizNet BizNet'
fi

echo -e  "      *** ${CYAN}Welcome to BizNet${NC} ***\n"

# SSH LAUNCHER ==========
# THIS IS NOT WORKING!!!!!!!

#if [ -z "$SSH_AUTH_SOCK" ]
#then
   # Check for a currently running instance of the agent
   #RUNNING_AGENT="`ps -ax | grep 'ssh-agent -s' | grep -v grep | wc -l | tr -d '[:space:]'`"
   #if [ "$RUNNING_AGENT" = "0" ]
   #then
        # Launch a new instance of the agent
        #ssh-agent -s &> $HOME/.ssh/ssh-agent
        #eval "$(ssh-agent -s)"
   #fi
   #eval `cat $HOME/.ssh/ssh-agent`
#fi

# INCLUDES ==========

# homebrew

if [[ ( -s /home/linuxbrew/.linuxbrew/bin/brew ) ]]; then
  eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
fi

if [[ ! -s $HOME/.bizconfig ]]; then
  echo -e "Enter ${CYAN}biznet${NC} for Configuration\n"
fi
