#!/bin/bash

if [[ $# != 1 ]]; then
  echo "Backs up file or folder per account. Target file argument reqired. -archive to initiate coude backup"
  exit 1
fi

case $1 in
  -archive)
    #echo rclone move pcloud:bizcloud/$BIZHOST/$USER pcloud:bizcloud/archive/$USER-$(date '+%F')|bash
    #echo rclone mkdir pcloud:bizcloud/$BIZHOST/$USER|bash
    echo rclone copy --use-mmap -P pcloud:bizcloud/$BIZHOST/$USER pcloud:bizcloud/archive/$USER-$(date '+%F')|bash
    exit 0
  ;;
esac

if [[ -d $(readlink -f $1) ]]; then
echo rclone sync --exclude='.git/**' --use-mmap -P $1 pcloud:bizcloud/$BIZHOST/$USER/$(basename $1)|bash
echo "Directory Copied"
else
echo rclone sync --exclude='.git/**' --use-mmap -P $1 pcloud:bizcloud/$BIZHOST/$USER/|bash
echo "File Copied"
fi

exit 0
