#!/bin/bash

if [[ $# != 1 ]]; then
  echo "Target file argument reqired"
  exit 1
fi

if [[ -d $HOME/bizcloud/master/$1 ]]; then
echo rclone sync -P pcloud:bizcloud/master/$1 ./$1|bash
echo "Directory Copied"
else
echo rclone sync -P pcloud:bizcloud/master/$1 .|bash
echo "File Copied"
fi

exit 0
