#!/bin/bash

if [[ $# != 1 ]]; then
  #gitdir=$PWD
  echo "Target repository required"
  exit 1
else
  gitdir=$1
fi

echo git remote add google ssh://noahmhughes@gmail.com@source.developers.google.com:2022/p/flash-realm-256405/r/$gitdir|bash
echo git remote add github ssh://git@github.com/bizfu/$gitdir|bash

exit 0
