#!/bin/bash
# ADD -vx after bash to echo expanded script
# or set -x/+x later

# VARIABLES ==========

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[1;36m'
NC='\033[0m'

input="ENTER"

# FUNCTIONS ==========

function pause {
  echo -e "${CYAN}Press [ENTER] to Continue${NC}"
  echo -e "(or [ESC] to return)\n"
  read -N 10000000 -t 0.01
  read -n 1 -s -r input
  case $input in
    $'\e')
      menu
    ;;
  esac
}

function completed {
  echo -e "${CYAN}Press [ENTER] to Continue${NC}"
  read -N 10000000 -t 0.01
  read -n 1 -s -r input
  case $input in
    $'\e')
      menu
    ;;
  esac
}

function initwiz {
  clear
  echo -e "\n1) Initialization Wizard\n"
  bizhost
  echo -e "\nOperation Complete..."
  completed
  menu
}

function bizhost {
  read -N 10000000 -t 0.01
  # echo -e "Configure Host Name? [Y/n]"
  read -n 1 -s -r -p "Configure Host Name? [Y/n]" input
  echo -e ""
  case $input in
  $'\e')
    menu
  ;;
  n|N)
    return
  ;;
  *)
    if [[ ( -s $HOME/.bizconfig ) ]]; then
      printf "\nCurrent Host Name: "
      echo -e ${CYAN}$(cat $HOME/.bizconfig)${NC}
    else
        echo -e "biznet" > $HOME/.bizconfig
    fi
    echo -e "\n(leave empty to skip)"
    read -p "Enter New Host Name: " bizconfig
    if [[ ! ( -z "$bizconfig" ) ]]; then
      echo -e "$bizconfig" > $HOME/.bizconfig
      if [[ ( -s $HOME/.bizconfig ) ]]; then
        printf "\nUpdated Host Name: "
        echo -e "${CYAN}$(cat $HOME/.bizconfig)${NC}\n"
      fi
    else
      printf "\nRetained Host Name: "
      echo -e "${CYAN}$(cat $HOME/.bizconfig)${NC}"
    fi
    ;;   
  esac
}

function installwiz {
  clear
  echo -e "\n2) Installation Wizard\n"
  sudo apt-get update
  sudo apt-get upgrade
  pause
  sudo apt-get install -y figlet
  pause
  # sudo apt-get install -y rclone
  curl https://rclone.org/install.sh | sudo bash
  echo -e "\nOperation Complete..."
  completed
  menu
}

function backwiz {
  clear
  echo -e "\n3) Backup Wizard\n"
  bizput $HOME/bizbin
  bizput $HOME/biznotes
  bizput $HOME/.gitconfig
  echo -e "\nOperation Complete..."
  completed
  menu
}

function finish {
stty echo
# restore screen
echo -e "\e[?1049l"
read -N 10000000 -t 0.01
exec bash
exit 0
}

function menu {
clear
if [[ ! -z $( command -v figlet ) ]]; then
  figlet 'BizNet'
else
  echo -e '\nBizNet BizNet BizNet BizNet'
fi
echo -e " ** ${CYAN}BizNet Setup Script${NC} **\n"

echo "1) Initialization Wizard"
echo "2) Installation Wizard"
echo "3) Backup Wizard"
echo "X) Exit"

echo -e "\nMake a Selection\n"
input
}

function input {
read -N 10000000 -t 0.01
read -n 1 -s -r input
case $input in
  1)
    initwiz
  ;;
  2)
    installwiz
  ;;
  3)
    backwiz
  ;;
  $'\e[A')
    # THIS IS NOT WORKING TO CAPTURE ARROW KEYS without -n 2
    stty -echo
    echo -e "${RED} <<<Invalid>>>${NC}"
    # Beep
    echo -e "\a"
    sleep 0.5
    stty echo
    menu
  ;;
  x|X|$'\e')
    finish
  ;;
  *)
    stty -echo
    echo -e "${RED} <<<Invalid>>>${NC}"
    # Beep
    echo -e "\a"
    sleep 0.2
    stty echo
    menu
  ;;
esac
}

# EXECUTE ==========

# save screen
echo -e "\e[?1049h"
# draw menu
menu

# ERROR ==========

# restore screen and exit
echo "ERROR - This should not have happened"
echo -e "\e[?1049l"
read -N 10000000 -t 0.01
exec bash
exit 1
