#!/bin/bash

if [[ $# != 1 ]]; then
  echo "Restores file or folder per account to home directory. Target file argument reqired. -archive to initiate cloud backup"
  exit 1
fi

if [[ -d $HOME/bizcloud/$BIZHOST/$USER/$1 ]]; then
echo rclone sync --use-mmap -P pcloud:bizcloud/$BIZHOST/$USER/$1 ./$1|bash
echo "Directory Copied"
else
echo rclone sync --use-mmap -P pcloud:bizcloud/$BIZHOST/$USER/$1 .|bash
echo "File Copied"
fi

exit 0
